env:
  global:
    - CC_TEST_REPORTER_ID=095397d4b930177b40f7a7d3c4b5f8055a786628d96f323e171a1e900509564c

language: ruby

cache: bundler

rvm:
  - 2.5.0

before_script:
  - bundle
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec
  # - bundle exec rubocop

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
